MACRO_FIXTURES = {
        "check_coinhive": [{
                "ip": 2917626385,
                "port": 8080,
                "http": {},
                "product": "MikroTik http proxy",
            }, {
                "ip": 3494743649,
                "port": 8080,
                "http": {},
                "product": "MikroTik http proxy",
            }],
        "weak_avtech": [{
                "ip": 1805602870,
                "port": 88,
                "product": "Avtech AVN801 network camera",
            }, {
                "ip": 412990438,
                "port": 8888,
                "http": {},
                "product": "Avtech AVN801 network camera",
            }, {
                "ip": 2264972081,
                "port": 88,
                "http": {},
                "product": "Avtech AVN801 network camera",
                }],
        "weak_jenkins": [{
                "ip": "35.183.208.63",
                "port": 8080,
                "http": {},
                "product": "Jenkins",
            }]
    }

IP_SEARCH_FIXTURES = [
        {
            "ip": 386931311,
            "port": 9090,
            "http": {},
            "product": "Avtech AVN801 network camera",
        },
        {
            "ip": 3639140288,
            "port": 8443,
            "http": {},
            "ssl": {},
        },
        {
            "ip": 3639140288,
            "port": 1723,
        },
        {
            "ip": 2925431185,
            "port": 8080,
            "http": {},
            "product": "MikroTik http proxy",
        },
        {
            "ip": "35.183.208.63",
            "port": 8080,
            "http": {},
            "product": "Jetty",
        }
    ]

WHOSEIP_FIXTURES = {
    '71.17.138.152': (200, {
        'arin_originas0_originautnums': [],
        'cidr0_cidrs': [{'length': 23, 'v4prefix': '71.17.138.0'}],
        'endAddress': '71.17.139.255',
        'entities': [{'entities': [{'events': [{'eventAction': 'last changed',
                                             'eventDate': '2010-07-07T10:07:13-04:00'},
                                            {'eventAction': 'registration',
                                             'eventDate': '2002-10-03T13:10:02-04:00'}],
                                 'handle': 'NOC178-ARIN',
                                 'links': [{'href': 'https://rdap.arin.net/registry/entity/NOC178-ARIN',
                                            'rel': 'self',
                                            'type': 'application/rdap+json',
                                            'value': 'https://rdap.arin.net/registry/ip/71.17.138.152/32'},
                                           {'href': 'https://whois.arin.net/rest/poc/NOC178-ARIN',
                                            'rel': 'alternate',
                                            'type': 'application/xml',
                                            'value': 'https://rdap.arin.net/registry/ip/71.17.138.152/32'}],
                                 'objectClassName': 'entity',
                                 'port43': 'whois.arin.net',
                                 'remarks': [{'description': ['ARIN has attempted '
                                                              'to validate the '
                                                              'data for this POC, '
                                                              'but has received no '
                                                              'response from the '
                                                              'POC since '
                                                              '2011-07-07'],
                                              'title': 'Unvalidated POC'}],
                                 'roles': ['noc'],
                                 'vcardArray': ['vcard',
                                                [['version', {}, 'text', '4.0'],
                                                 ['adr',
                                                  {'label': '1855 Lorne Street\n'
                                                            'Regina\n'
                                                            'SK\n'
                                                            'S4P-3N1\n'
                                                            'Canada'},
                                                  'text',
                                                  ['', '', '', '', '', '', '']],
                                                 ['fn',
                                                  {},
                                                  'text',
                                                  'Network Operations Center'],
                                                 ['org',
                                                  {},
                                                  'text',
                                                  'Network Operations Center'],
                                                 ['kind', {}, 'text', 'group'],
                                                 ['email',
                                                  {},
                                                  'text',
                                                  'NetworkAnalyst.BCSC@sasktel.sk.ca'],
                                                 ['tel',
                                                  {'type': ['work', 'voice']},
                                                  'text',
                                                  '+1-306-777-1458']]]},
                                {'events': [{'eventAction': 'last changed',
                                             'eventDate': '2002-10-03T13:00:06-04:00'},
                                            {'eventAction': 'registration',
                                             'eventDate': '2002-10-03T13:00:06-04:00'}],
                                 'handle': 'SASKN-ARIN',
                                 'links': [{'href': 'https://rdap.arin.net/registry/entity/SASKN-ARIN',
                                            'rel': 'self',
                                            'type': 'application/rdap+json',
                                            'value': 'https://rdap.arin.net/registry/ip/71.17.138.152/32'},
                                           {'href': 'https://whois.arin.net/rest/poc/SASKN-ARIN',
                                            'rel': 'alternate',
                                            'type': 'application/xml',
                                            'value': 'https://rdap.arin.net/registry/ip/71.17.138.152/32'}],
                                 'objectClassName': 'entity',
                                 'port43': 'whois.arin.net',
                                 'remarks': [{'description': ['ARIN has attempted '
                                                              'to validate the '
                                                              'data for this POC, '
                                                              'but has received no '
                                                              'response from the '
                                                              'POC since '
                                                              '2010-07-08'],
                                              'title': 'Unvalidated POC'}],
                                 'roles': ['abuse'],
                                 'vcardArray': ['vcard',
                                                [['version', {}, 'text', '4.0'],
                                                 ['adr',
                                                  {'label': '1825 Lorne Street - '
                                                            '7th\n'
                                                            'Regina\n'
                                                            'SK\n'
                                                            'S4P-3Y2\n'
                                                            'Canada'},
                                                  'text',
                                                  ['', '', '', '', '', '', '']],
                                                 ['fn',
                                                  {},
                                                  'text',
                                                  'Sasknet Abuse'],
                                                 ['org',
                                                  {},
                                                  'text',
                                                  'Sasknet Abuse'],
                                                 ['kind', {}, 'text', 'group'],
                                                 ['email',
                                                  {},
                                                  'text',
                                                  'abuse@sasktel.net'],
                                                 ['tel',
                                                  {'type': ['work', 'voice']},
                                                  'text',
                                                  '+1-306-761-6076']]]},
                                {'events': [{'eventAction': 'last changed',
                                             'eventDate': '2003-01-29T18:00:09-05:00'},
                                            {'eventAction': 'registration',
                                             'eventDate': '2003-01-29T18:00:09-05:00'}],
                                 'handle': 'WANEC-ARIN',
                                 'links': [{'href': 'https://rdap.arin.net/registry/entity/WANEC-ARIN',
                                            'rel': 'self',
                                            'type': 'application/rdap+json',
                                            'value': 'https://rdap.arin.net/registry/ip/71.17.138.152/32'},
                                           {'href': 'https://whois.arin.net/rest/poc/WANEC-ARIN',
                                            'rel': 'alternate',
                                            'type': 'application/xml',
                                            'value': 'https://rdap.arin.net/registry/ip/71.17.138.152/32'}],
                                 'objectClassName': 'entity',
                                 'port43': 'whois.arin.net',
                                 'remarks': [{'description': ['ARIN has attempted '
                                                              'to validate the '
                                                              'data for this POC, '
                                                              'but has received no '
                                                              'response from the '
                                                              'POC since '
                                                              '2010-12-11'],
                                              'title': 'Unvalidated POC'}],
                                 'roles': ['technical'],
                                 'vcardArray': ['vcard',
                                                [['version', {}, 'text', '4.0'],
                                                 ['adr',
                                                  {'label': '2121 Sask. DR. F9\n'
                                                            'Regina\n'
                                                            'SK\n'
                                                            'S4P-3Y2\n'
                                                            'Canada'},
                                                  'text',
                                                  ['', '', '', '', '', '', '']],
                                                 ['fn',
                                                  {},
                                                  'text',
                                                  'WIDE AREA NETWORK ENGINEERING '
                                                  'CENTER'],
                                                 ['org',
                                                  {},
                                                  'text',
                                                  'WIDE AREA NETWORK ENGINEERING '
                                                  'CENTER'],
                                                 ['kind', {}, 'text', 'group'],
                                                 ['email',
                                                  {},
                                                  'text',
                                                  'wanec@sasktel.sk.ca'],
                                                 ['tel',
                                                  {'type': ['work', 'voice']},
                                                  'text',
                                                  '+1-306-777-3238']]]},
                                {'events': [{'eventAction': 'last changed',
                                             'eventDate': '2019-07-25T09:36:18-04:00'}],
                                 'handle': 'SA30-ORG-ARIN',
                                 'links': [{'href': 'https://rdap.arin.net/registry/entity/SA30-ORG-ARIN',
                                            'rel': 'self',
                                            'type': 'application/rdap+json',
                                            'value': 'https://rdap.arin.net/registry/ip/71.17.138.152/32'},
                                           {'href': 'https://whois.arin.net/rest/poc/SA30-ORG-ARIN',
                                            'rel': 'alternate',
                                            'type': 'application/xml',
                                            'value': 'https://rdap.arin.net/registry/ip/71.17.138.152/32'}],
                                 'objectClassName': 'entity',
                                 'port43': 'whois.arin.net',
                                 'roles': ['administrative'],
                                 'status': ['validated'],
                                 'vcardArray': ['vcard',
                                                [['version', {}, 'text', '4.0'],
                                                 ['adr',
                                                  {'label': '9th Flr, 2121 '
                                                            'Saskatchewan Dr.\n'
                                                            'Regina\n'
                                                            'SK\n'
                                                            'S4P-3Y2\n'
                                                            'Canada'},
                                                  'text',
                                                  ['', '', '', '', '', '', '']],
                                                 ['fn', {}, 'text', 'SaskTel'],
                                                 ['org', {}, 'text', 'SaskTel'],
                                                 ['kind', {}, 'text', 'group'],
                                                 ['email',
                                                  {},
                                                  'text',
                                                  'sasktel.wanec@sasktel.com'],
                                                 ['tel',
                                                  {'type': ['work', 'voice']},
                                                  'text',
                                                  '+1-306-777-3088']]]}],
                   'events': [{'eventAction': 'last changed',
                               'eventDate': '2003-07-08T14:44:08-04:00'},
                              {'eventAction': 'registration',
                               'eventDate': '2001-07-10T23:00:00-04:00'}],
                   'handle': 'SWANEC',
                   'links': [{'href': 'https://rdap.arin.net/registry/entity/SWANEC',
                              'rel': 'self',
                              'type': 'application/rdap+json',
                              'value': 'https://rdap.arin.net/registry/ip/71.17.138.152/32'},
                             {'href': 'https://whois.arin.net/rest/org/SWANEC',
                              'rel': 'alternate',
                              'type': 'application/xml',
                              'value': 'https://rdap.arin.net/registry/ip/71.17.138.152/32'}],
                   'objectClassName': 'entity',
                   'port43': 'whois.arin.net',
                   'roles': ['registrant'],
                   'vcardArray': ['vcard',
                                  [['version', {}, 'text', '4.0'],
                                   ['fn',
                                    {},
                                    'text',
                                    'SaskTel Wide Area Network Engineering Center'],
                                   ['adr',
                                    {'label': '2121 Sask. Dr F9\n'
                                              'Regina\n'
                                              'SK\n'
                                              'S4P-3Y2\n'
                                              'Canada'},
                                    'text',
                                    ['', '', '', '', '', '', '']],
                                   ['kind', {}, 'text', 'org']]]}],
        'events': [{'eventAction': 'last changed',
                 'eventDate': '2015-02-19T12:41:05-05:00'},
                {'eventAction': 'registration',
                 'eventDate': '2015-02-19T12:41:05-05:00'}],
        'handle': 'NET-71-17-138-0-1',
        'ipVersion': 'v4',
        'links': [{'href': 'https://rdap.arin.net/registry/ip/71.17.138.0',
                'rel': 'self',
                'type': 'application/rdap+json',
                'value': 'https://rdap.arin.net/registry/ip/71.17.138.152/32'},
               {'href': 'https://whois.arin.net/rest/net/NET-71-17-138-0-1',
                'rel': 'alternate',
                'type': 'application/xml',
                'value': 'https://rdap.arin.net/registry/ip/71.17.138.152/32'},
               {'href': 'https://rdap.arin.net/registry/ip/71.17.0.0/16',
                'rel': 'up',
                'type': 'application/rdap+json',
                'value': 'https://rdap.arin.net/registry/ip/71.17.138.152/32'}],
        'name': 'WANEC-1720',
        'notices': [{'description': ['By using the ARIN RDAP/Whois service, you are '
                                  'agreeing to the RDAP/Whois Terms of Use'],
                  'links': [{'href': 'https://www.arin.net/resources/registry/whois/tou/',
                             'rel': 'about',
                             'type': 'text/html',
                             'value': 'https://rdap.arin.net/registry/ip/71.17.138.152/32'}],
                  'title': 'Terms of Service'},
                 {'description': ['If you see inaccuracies in the results, please '
                                  'visit: '],
                  'links': [{'href': 'https://www.arin.net/resources/registry/whois/inaccuracy_reporting/',
                             'rel': 'about',
                             'type': 'text/html',
                             'value': 'https://rdap.arin.net/registry/ip/71.17.138.152/32'}],
                  'title': 'Whois Inaccuracy Reporting'},
                 {'description': ['Copyright 1997-2020, American Registry for '
                                  'Internet Numbers, Ltd.'],
                  'title': 'Copyright Notice'}],
        'objectClassName': 'ip network',
        'parentHandle': 'NET-71-17-0-0-1',
        'port43': 'whois.arin.net',
        'rdapConformance': ['rdap_level_0', 'cidr0', 'arin_originas0'],
        'remarks': [{'description': ['hsdbsk'], 'title': 'Registration Comments'}],
        'startAddress': '71.17.138.0',
        'status': ['active'],
        'type': 'ASSIGNMENT'}),

    '109.87.56.48': (200, {
        'country': 'UA',
        'endAddress': '109.87.56.255',
        'entities': [{'handle': 'OVY5-RIPE',
                   'objectClassName': 'entity',
                   'roles': ['technical', 'administrative']},
                  {'handle': 'SALTOVKAMNT',
                   'objectClassName': 'entity',
                   'roles': ['registrant']},
                  {'handle': 'TRIOLANMNT',
                   'objectClassName': 'entity',
                   'roles': ['registrant']},
                  {'handle': 'YT1496-RIPE',
                   'objectClassName': 'entity',
                   'roles': ['technical', 'administrative']},
                  {'entities': [{'handle': 'TRIOLANMNT',
                                 'objectClassName': 'entity',
                                 'roles': ['registrant']}],
                   'handle': 'AR37924-RIPE',
                   'objectClassName': 'entity',
                   'roles': ['abuse'],
                   'vcardArray': ['vcard',
                                  [['version', {}, 'text', '4.0'],
                                   ['fn', {}, 'text', 'Abuse Role'],
                                   ['kind', {}, 'text', 'group'],
                                   ['adr',
                                    {'label': 'Ukraine, Kyiv, Prirechnaya 25A, '
                                              'office 7'},
                                    'text',
                                    ['', '', '', '', '', '', '']],
                                   ['email',
                                    {'type': 'email'},
                                    'text',
                                    'noc@triolan.com'],
                                   ['email',
                                    {'type': 'abuse'},
                                    'text',
                                    'abuse@triolan.com.ua']]]}],
        'events': [{'eventAction': 'last changed',
                 'eventDate': '2019-07-18T13:40:42Z'}],
        'handle': '109.87.56.0 - 109.87.56.255',
        'ipVersion': 'v4',
        'links': [{'href': 'https://rdap.db.ripe.net/ip/109.87.56.48/32',
                'rel': 'self',
                'value': 'https://rdap.db.ripe.net/ip/109.87.56.48/32'},
               {'href': 'http://www.ripe.net/data-tools/support/documentation/terms',
                'rel': 'copyright',
                'value': 'http://www.ripe.net/data-tools/support/documentation/terms'}],
        'name': 'TRIOLAN',
        'notices': [{'description': ['This output has been filtered.'],
                  'title': 'Filtered'},
                 {'description': ['Objects returned came from source', 'RIPE'],
                  'title': 'Source'},
                 {'description': ['This is the RIPE Database query service. The '
                                  'objects are in RDAP format.'],
                  'links': [{'href': 'http://www.ripe.net/db/support/db-terms-conditions.pdf',
                             'rel': 'terms-of-service',
                             'type': 'application/pdf',
                             'value': 'https://rdap.db.ripe.net/ip/109.87.56.48/32'}],
                  'title': 'Terms and Conditions'}],
        'objectClassName': 'ip network',
        'parentHandle': '109.86.0.0 - 109.87.255.255',
        'port43': 'whois.ripe.net',
        'rdapConformance': ['rdap_level_0'],
        'startAddress': '109.87.56.0',
        'type': 'ASSIGNED PA'}),

    'ci.jwfh.ca': (404, {
        'description': ['Domain not found'],
        'errorCode': 404,
        'notices': [{'description': ['Service subject to Terms of Use.'],
                  'links': [{'href': 'https://cira.ca/legal-policy-compliance/website-terms-use',
                             'rel': 'related',
                             'type': 'text/html'}],
                  'title': 'Terms of Service'},
                 {'description': ['URL of the ICANN RDDS Inaccuracy Complaint '
                                  'Form: https://icann.org/wicf'],
                  'links': [{'href': 'https://icann.org/wicf',
                             'rel': 'related',
                             'type': 'text/html'}],
                  'title': 'RDDS Inaccuracy Complaint Form'}],
        'rdapConformance': ['icann_rdap_response_profile_0',
                         'icann_rdap_technical_implementation_guide_0',
                         'rdap_level_0'],
        'title': 'Domain not found'}),

    'build.automotivelinux.org': (200, {
        'entities': [{'entities': [{'objectClassName': 'entity',
                                 'roles': ['abuse'],
                                 'vcardArray': ['vcard',
                                                [['version', {}, 'text', '4.0'],
                                                 ['role', {}, 'text', 'abuse'],
                                                 ['tel',
                                                  {'type': ['voice']},
                                                  'uri',
                                                  'tel:+1.4252982646'],
                                                 ['email',
                                                  {},
                                                  'text',
                                                  'abuse@enom.com']]]}],
                   'events': [{'eventAction': 'registration',
                               'eventDate': '2003-01-22T21:23:23.000Z'},
                              {'eventAction': 'last changed',
                               'eventDate': '2020-06-12T13:51:15.020Z'}],
                   'handle': '48',
                   'links': [{'href': 'https://rdap.publicinterestregistry.net/rdap/org/entity/48',
                              'rel': 'alternate',
                              'type': 'application/rdap+json',
                              'value': 'https://rdap.publicinterestregistry.net/rdap/org/entity/48'}],
                   'objectClassName': 'entity',
                   'publicIds': [{'identifier': '48', 'type': 'IANA Registrar ID'}],
                   'roles': ['registrar'],
                   'vcardArray': ['vcard',
                                  [['version', {}, 'text', '4.0'],
                                   ['fn', {}, 'text', 'eNom, Inc.'],
                                   ['org', {}, 'text', 'eNom, Inc.'],
                                   ['role', {}, 'text', 'registrar'],
                                   ['adr',
                                    {'cc': 'CA'},
                                    'text',
                                    ['',
                                     '',
                                     '96 Mowat Ave',
                                     'Toronto',
                                     'ON',
                                     'M6K 3M1',
                                     '']],
                                   ['tel',
                                    {'type': ['voice']},
                                    'uri',
                                    'tel:+1.4165350123;ext=1451'],
                                   ['tel',
                                    {'type': ['fax']},
                                    'uri',
                                    'tel:+1.4165250123;ext=1452'],
                                   ['email',
                                    {},
                                    'text',
                                    'tucows_Registrar@tucows.com']]]},
                  {'objectClassName': 'entity',
                   'remarks': [{'description': ['Some of the data in this object '
                                                'has been removed'],
                                'title': 'REDACTED FOR PRIVACY',
                                'type': 'object redacted due to authorization'}],
                   'roles': ['registrant'],
                   'vcardArray': ['vcard',
                                  [['version', {}, 'text', '4.0'],
                                   ['org', {}, 'text', 'Data Protected'],
                                   ['role', {}, 'text', 'registrant'],
                                   ['adr',
                                    {'cc': 'US'},
                                    'text',
                                    ['', '', '', '', 'WA', '', '']]]]}],
        'events': [{'eventAction': 'registration',
                 'eventDate': '2013-04-30T15:32:11.741Z'},
                {'eventAction': 'last changed',
                 'eventDate': '2019-12-18T00:21:56.299Z'},
                {'eventAction': 'expiration',
                 'eventDate': '2021-04-30T15:32:11.741Z'},
                {'eventAction': 'last update of RDAP database',
                 'eventDate': '2020-06-15T05:20:47.406Z'}],
        'handle': 'D168575853-LROR',
        'ldhName': 'automotivelinux.org',
        'links': [{'href': 'https://rdap.publicinterestregistry.net/rdap/org/domain/automotivelinux.org',
                'rel': 'self',
                'type': 'application/rdap+json',
                'value': 'https://rdap.publicinterestregistry.net/rdap/org/domain/automotivelinux.org'},
               {'href': 'https://enom.rdap.tucows.com/domain/automotivelinux.org',
                'rel': 'related',
                'type': 'application/rdap+json',
                'value': 'https://enom.rdap.tucows.com/domain/automotivelinux.org'}],
        'nameservers': [{'events': [{'eventAction': 'registration',
                                  'eventDate': '2010-07-07T19:13:37.000Z'},
                                 {'eventAction': 'last changed',
                                  'eventDate': '2012-05-16T07:23:48.092Z'}],
                      'handle': 'H56717705-LROR',
                      'ldhName': 'ns1.dnsimple.com',
                      'objectClassName': 'nameserver',
                      'status': ['active', 'associated']},
                     {'events': [{'eventAction': 'registration',
                                  'eventDate': '2010-07-07T19:13:37.000Z'},
                                 {'eventAction': 'last changed',
                                  'eventDate': '2012-05-16T07:23:48.116Z'}],
                      'handle': 'H56717706-LROR',
                      'ldhName': 'ns2.dnsimple.com',
                      'objectClassName': 'nameserver',
                      'status': ['active', 'associated']},
                     {'events': [{'eventAction': 'registration',
                                  'eventDate': '2010-12-07T18:58:12.000Z'}],
                      'handle': 'H56952058-LROR',
                      'ldhName': 'ns3.dnsimple.com',
                      'objectClassName': 'nameserver',
                      'status': ['active', 'associated']},
                     {'events': [{'eventAction': 'registration',
                                  'eventDate': '2010-12-07T18:58:12.000Z'}],
                      'handle': 'H56952059-LROR',
                      'ldhName': 'ns4.dnsimple.com',
                      'objectClassName': 'nameserver',
                      'status': ['active', 'associated']}],
        'notices': [{'description': ['Access to Public Interest Registry RDAP '
                                  'information is provided to assist persons in '
                                  'determining the contents of a domain name '
                                  'registration record in the Public Interest '
                                  'registry database. The data in this record is '
                                  'provided by Public Interest Registry for '
                                  'informational purposes only, and Public '
                                  'Interest Registry does not guarantee its '
                                  'accuracy. This service is intended only for '
                                  'query-based access. You agree that you will use '
                                  'this data only for lawful purposes and that, '
                                  'under no circumstances will you use this data '
                                  'to(a) allow, enable, or otherwise support the '
                                  'transmission by e-mail, telephone, or facsimile '
                                  'of mass unsolicited, commercial advertising or '
                                  'solicitations to entities other than the data '
                                  "recipient's own existing customers; or (b) "
                                  'enable high volume, automated, electronic '
                                  'processes that send queries or data to the '
                                  'systems of Registry Operator, a Registrar, or '
                                  'Afilias except as reasonably necessary to '
                                  'register domain names or modify existing '
                                  'registrations. All rights reserved. Public '
                                  'Interest Registry reserves the right to modify '
                                  'these terms at any time. By submitting this '
                                  'query, you agree to abide by this policy.'],
                  'links': [{'href': 'https://rdap.publicinterestregistry.net/rdap/org/terms_of_use',
                             'rel': 'alternate',
                             'type': 'text/html'}],
                  'title': 'Terms of Use'},
                 {'description': ['For more information on domain status codes, '
                                  'please visit https://icann.org/epp'],
                  'links': [{'href': 'https://icann.org/epp', 'rel': 'related'}],
                  'title': 'Status Codes'},
                 {'description': ['URL of the ICANN RDDS Inaccuracy Complaint '
                                  'Form: https://www.icann.org/wicf'],
                  'links': [{'href': 'https://www.icann.org/wicf',
                             'rel': 'related'}],
                  'title': 'RDDS Inaccuracy Complaint Form'}],
        'objectClassName': 'domain',
        'rdapConformance': ['rdap_level_0',
                         'icann_rdap_response_profile_0',
                         'icann_rdap_technical_implementation_guide_0'],
        'secureDNS': {'delegationSigned': False},
        'status': ['client transfer prohibited']}),
 
    'jwfh.ca': (200, {
        'entities': [{'entities': [{'objectClassName': 'entity',
                                 'publicIds': [{'identifier': '',
                                                'type': 'IANA Registrar ID'}],
                                 'roles': ['abuse'],
                                 'vcardArray': ['vcard',
                                                [['version', {}, 'text', '4.0'],
                                                 ['fn',
                                                  {},
                                                  'text',
                                                  'Abuse Contact'],
                                                 ['kind', {}, 'text', 'individual'],
                                                 ['role', {}, 'text', 'abuse'],
                                                 ['adr',
                                                  {},
                                                  'text',
                                                  ['', '', '', '', '', '', '']],
                                                 ['tel',
                                                  {'type': ['voice']},
                                                  'uri',
                                                  'tel:'],
                                                 ['email', {}, 'text', ''],
                                                 ['url',
                                                  {'type': 'home'},
                                                  'uri',
                                                  'ca.godaddy.com']]]}],
                   'objectClassName': 'entity',
                   'publicIds': [{'identifier': '', 'type': 'IANA Registrar ID'}],
                   'roles': ['registrar'],
                   'vcardArray': ['vcard',
                                  [['version', {}, 'text', '4.0'],
                                   ['fn',
                                    {},
                                    'text',
                                    'Go Daddy Domains Canada, Inc'],
                                   ['kind', {}, 'text', 'org'],
                                   ['role', {}, 'text', 'registrar'],
                                   ['adr',
                                    {},
                                    'text',
                                    ['', '', '', '', '', '', '']],
                                   ['url',
                                    {'type': 'home'},
                                    'uri',
                                    'ca.godaddy.com']]]},
                  {'handle': 'REDACTED FOR PRIVACY',
                   'objectClassName': 'entity',
                   'publicIds': [{'identifier': 'REDACTED FOR PRIVACY',
                                  'type': 'ROID'}],
                   'remarks': [{'description': ['Some of the data in this object '
                                                'has been removed'],
                                'title': 'REDACTED FOR PRIVACY',
                                'type': 'object redacted due to authorization'},
                               {'description': ['Please query the RDDS service of '
                                                'the Registrar of Record '
                                                'identified in this output for '
                                                'information on how to contact the '
                                                'Registrant of the queried domain '
                                                'name'],
                                'title': 'EMAIL REDACTED FOR PRIVACY',
                                'type': 'object redacted due to authorization'}],
                   'roles': ['registrant'],
                   'vcardArray': ['vcard',
                                  [['version', {}, 'text', '4.0'],
                                   ['fn', {}, 'text', 'REDACTED FOR PRIVACY'],
                                   ['kind', {}, 'text', 'individual'],
                                   ['org', {}, 'text', 'REDACTED FOR PRIVACY'],
                                   ['role', {}, 'text', 'registrant'],
                                   ['adr',
                                    {},
                                    'text',
                                    ['',
                                     '',
                                     'REDACTED FOR PRIVACY',
                                     'REDACTED FOR PRIVACY',
                                     'NL',
                                     'REDACTED FOR PRIVACY',
                                     'REDACTED FOR PRIVACY']],
                                   ['tel',
                                    {'type': ['voice']},
                                    'uri',
                                    'tel:REDACTED FOR PRIVACY'],
                                   ['tel',
                                    {'type': ['fax']},
                                    'uri',
                                    'tel:REDACTED FOR PRIVACY'],
                                   ['email',
                                    {},
                                    'text',
                                    'EMAIL REDACTED FOR PRIVACY'],
                                   ['url',
                                    {'type': 'home'},
                                    'uri',
                                    'REDACTED FOR PRIVACY']]]},
                  {'handle': 'REDACTED FOR PRIVACY',
                   'objectClassName': 'entity',
                   'publicIds': [{'identifier': 'REDACTED FOR PRIVACY',
                                  'type': 'ROID'}],
                   'remarks': [{'description': ['Some of the data in this object '
                                                'has been removed'],
                                'title': 'REDACTED FOR PRIVACY',
                                'type': 'object redacted due to authorization'},
                               {'description': ['Please query the RDDS service of '
                                                'the Registrar of Record '
                                                'identified in this output for '
                                                'information on how to contact the '
                                                'Registrant of the queried domain '
                                                'name'],
                                'title': 'EMAIL REDACTED FOR PRIVACY',
                                'type': 'object redacted due to authorization'}],
                   'roles': ['administrative'],
                   'vcardArray': ['vcard',
                                  [['version', {}, 'text', '4.0'],
                                   ['fn', {}, 'text', 'REDACTED FOR PRIVACY'],
                                   ['kind', {}, 'text', 'individual'],
                                   ['org', {}, 'text', 'REDACTED FOR PRIVACY'],
                                   ['role', {}, 'text', 'administrative'],
                                   ['adr',
                                    {},
                                    'text',
                                    ['',
                                     '',
                                     'REDACTED FOR PRIVACY',
                                     'REDACTED FOR PRIVACY',
                                     'REDACTED FOR PRIVACY',
                                     'REDACTED FOR PRIVACY',
                                     'REDACTED FOR PRIVACY']],
                                   ['tel',
                                    {'type': ['voice']},
                                    'uri',
                                    'tel:REDACTED FOR PRIVACY'],
                                   ['tel',
                                    {'type': ['fax']},
                                    'uri',
                                    'tel:REDACTED FOR PRIVACY'],
                                   ['email',
                                    {},
                                    'text',
                                    'EMAIL REDACTED FOR PRIVACY'],
                                   ['url',
                                    {'type': 'home'},
                                    'uri',
                                    'REDACTED FOR PRIVACY']]]},
                  {'handle': 'REDACTED FOR PRIVACY',
                   'objectClassName': 'entity',
                   'publicIds': [{'identifier': 'REDACTED FOR PRIVACY',
                                  'type': 'ROID'}],
                   'remarks': [{'description': ['Some of the data in this object '
                                                'has been removed'],
                                'title': 'REDACTED FOR PRIVACY',
                                'type': 'object redacted due to authorization'},
                               {'description': ['Please query the RDDS service of '
                                                'the Registrar of Record '
                                                'identified in this output for '
                                                'information on how to contact the '
                                                'Registrant of the queried domain '
                                                'name'],
                                'title': 'EMAIL REDACTED FOR PRIVACY',
                                'type': 'object redacted due to authorization'}],
                   'roles': ['technical'],
                   'vcardArray': ['vcard',
                                  [['version', {}, 'text', '4.0'],
                                   ['fn', {}, 'text', 'REDACTED FOR PRIVACY'],
                                   ['kind', {}, 'text', 'individual'],
                                   ['org', {}, 'text', 'REDACTED FOR PRIVACY'],
                                   ['role', {}, 'text', 'technical'],
                                   ['adr',
                                    {},
                                    'text',
                                    ['',
                                     '',
                                     'REDACTED FOR PRIVACY',
                                     'REDACTED FOR PRIVACY',
                                     'REDACTED FOR PRIVACY',
                                     'REDACTED FOR PRIVACY',
                                     'REDACTED FOR PRIVACY']],
                                   ['tel',
                                    {'type': ['voice']},
                                    'uri',
                                    'tel:REDACTED FOR PRIVACY'],
                                   ['tel',
                                    {'type': ['fax']},
                                    'uri',
                                    'tel:REDACTED FOR PRIVACY'],
                                   ['email',
                                    {},
                                    'text',
                                    'EMAIL REDACTED FOR PRIVACY'],
                                   ['url',
                                    {'type': 'home'},
                                    'uri',
                                    'REDACTED FOR PRIVACY']]]},
                  {'handle': 'REDACTED FOR PRIVACY',
                   'objectClassName': 'entity',
                   'publicIds': [{'identifier': 'REDACTED FOR PRIVACY',
                                  'type': 'ROID'}],
                   'remarks': [{'description': ['Some of the data in this object '
                                                'has been removed'],
                                'title': 'REDACTED FOR PRIVACY',
                                'type': 'object redacted due to authorization'},
                               {'description': ['Please query the RDDS service of '
                                                'the Registrar of Record '
                                                'identified in this output for '
                                                'information on how to contact the '
                                                'Registrant of the queried domain '
                                                'name'],
                                'title': 'EMAIL REDACTED FOR PRIVACY',
                                'type': 'object redacted due to authorization'}],
                   'roles': ['billing'],
                   'vcardArray': ['vcard',
                                  [['version', {}, 'text', '4.0'],
                                   ['fn', {}, 'text', 'REDACTED FOR PRIVACY'],
                                   ['kind', {}, 'text', 'individual'],
                                   ['org', {}, 'text', 'REDACTED FOR PRIVACY'],
                                   ['role', {}, 'text', 'billing'],
                                   ['adr',
                                    {},
                                    'text',
                                    ['',
                                     '',
                                     'REDACTED FOR PRIVACY',
                                     'REDACTED FOR PRIVACY',
                                     'REDACTED FOR PRIVACY',
                                     'REDACTED FOR PRIVACY',
                                     'REDACTED FOR PRIVACY']],
                                   ['tel',
                                    {'type': ['voice']},
                                    'uri',
                                    'tel:REDACTED FOR PRIVACY'],
                                   ['tel',
                                    {'type': ['fax']},
                                    'uri',
                                    'tel:REDACTED FOR PRIVACY'],
                                   ['email',
                                    {},
                                    'text',
                                    'EMAIL REDACTED FOR PRIVACY'],
                                   ['url',
                                    {'type': 'home'},
                                    'uri',
                                    'REDACTED FOR PRIVACY']]]}],
        'events': [{'eventAction': 'registration',
                 'eventDate': '2016-07-08T20:38:49Z'},
                {'eventAction': 'expiration', 'eventDate': '2020-07-08T20:38:49Z'},
                {'eventAction': 'last changed',
                 'eventDate': '2019-08-22T20:46:38Z'},
                {'eventAction': 'last update of RDAP database',
                 'eventDate': '2020-06-15T05:11:20Z'}],
        'handle': '30567007-CIRA',
        'ldhName': 'jwfh.ca',
        'links': [{'href': 'https://rdap.ca.fury.ca/rdap//domain/jwfh.ca',
                'rel': 'self',
                'title': 'Authoritative URL for this resource',
                'type': 'application/rdap+json'}],
        'nameservers': [{'ldhName': 'george.ns.cloudflare.com',
                      'objectClassName': 'nameserver'},
                     {'ldhName': 'ines.ns.cloudflare.com',
                      'objectClassName': 'nameserver'}],
        'notices': [{'description': ['For more information on domain status codes, '
                                  'please visit https://icann.org/epp'],
                  'links': [{'href': 'https://icann.org/epp',
                             'rel': 'related',
                             'type': 'text/html'}],
                  'title': 'Status Codes'},
                 {'description': ['Service subject to Terms of Use.'],
                  'links': [{'href': 'https://cira.ca/legal-policy-compliance/website-terms-use',
                             'rel': 'related',
                             'type': 'text/html'}],
                  'title': 'Terms of Service'},
                 {'description': ['URL of the ICANN RDDS Inaccuracy Complaint '
                                  'Form: https://icann.org/wicf'],
                  'links': [{'href': 'https://icann.org/wicf',
                             'rel': 'related',
                             'type': 'text/html'}],
                  'title': 'RDDS Inaccuracy Complaint Form'}],
        'objectClassName': 'domain',
        'port43': 'whois.ca.fury.ca',
        'rdapConformance': ['icann_rdap_response_profile_0',
                         'icann_rdap_technical_implementation_guide_0',
                         'rdap_level_0'],
        'secureDNS': {'delegationSigned': False},
        'status': ['client delete prohibited',
                'client transfer prohibited',
                'client update prohibited'],
        'unicodeName': 'jwfh.ca',
        'whoisReferralUrl': 'ca.godaddy.com'}),
    }

FIXTURES = dict(MACRO_FIXTURES=MACRO_FIXTURES,
        IP_SEARCH_FIXTURES=IP_SEARCH_FIXTURES,
        WHOSEIP_FIXTURES=WHOSEIP_FIXTURES)


